jobs:
  build:
    strategy:
      matrix:
        os: [macos-11, ubuntu-22.04, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set separator
        run: echo "::set-output name=separator::${{ if eq(matrix.os, 'windows-latest') }};{{ else }}:{{ endif }}"
        id: set-separator

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
      - name: Create virtual environment
        run: python -m venv env
        
      - name: Activate virtual environment
        run: source env/bin/activate
        if: runner.os != 'Windows'
        
      - name: Activate virtual environment
        run: env\Scripts\activate.bat
        if: runner.os == 'Windows'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          python -m textblob.download_corpora
          python -m spacy download en_core_web_sm

      - name: Build Executable
        run: |
          pyinstaller -D -n Fudgify --add-data "static${{ steps.set-separator.outputs.separator }}static" --add-data "templates${{ steps.set-separator.outputs.separator }}templates" --add-data "data${{ steps.set-separator.outputs.separator }}data" --collect-all moviepy --collect-all textblob --collect-all spacy --hiddenimport srsly.msgpack.util --collect-all flask_socketio --collect-all en_core_web_sm --additional-hooks-dir=hooks -i static/img/App_Icon.png --noconfirm app.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            dist/