name: Build binaries
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-11, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          python install_deps.py
      
      - name: Install FFMpeg on macOS
        run: |
          brew tap homebrew-ffmpeg/ffmpeg
          brew install homebrew-ffmpeg/ffmpeg/ffmpeg
        if: runner.os != 'Windows'

      - name: Build Executable
        run: |
          pyinstaller --clean --noconfirm Fudgify.spec
        if: runner.os != 'Windows'
      
      - name: Build Executable
        run: |
          pyinstaller --clean --noconfirm Fudgify.spec
          Compress-Archive -Path dist/ -DestinationPath Fudgify-Windows.zip
        if: runner.os == 'Windows'
      
      - name: Cleanup
        run: |
          rm -rf dist/Fudgify
          tar czf Fudgify-macOS.tar.gz dist/
        if: runner.os == 'macOS'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            Fudgify-${{ runner.os }}.*