name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Package app with PyInstaller
      run: |
        python -m nuitka --include-data-dir="static"="static" --include-data-dir="templates"="templates" --include-data-dir="data"="data" --onefile --follow-imports app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: TwitterVideoMakerBot
        path: app.dist/
